# Generated by Django 4.2.25 on 2025-10-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_rename_sent_at_message_timestamp_message_edited_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagehistory',
            old_name='edited_content',
            new_name='old_content',
        ),
    ]
