version: '3.8'

services: 
  web:    
    build: .
    restart: always
    ports:     
      - "8000:8000"   
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    networks:      
      - backend  
    # volumes:      
    #   - shared-volume:/usr/share/nginx/html
    depends_on:
      - db

  db:   
    image: mysql:8.0
    restart: always

    networks:     
      - backend    
    volumes:      
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD: /run/secrets/mysql_password
      - MYSQL_PASSWORD: /run/secrets/mysql_password
      - MYSQL_USER: ${MYSQL_USER}
      - MYSQL_DATABASE: ${MYSQL_DATABASE}
    secrets:
      - mysql_password

networks:  
  backend:   
    driver: bridge

volumes:  
  mysql_data: 
secrets:
  mysql_password:
    file: ./mysql_password.txt