# Generated by Django 5.2.6 on 2025-09-21 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_conversation_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='conversation', to='chats.message'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participants_id',
            field=models.ManyToManyField(blank=True, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
